import { HttpEvent, HttpHandler, HttpInterceptor, HttpRequest } from "@angular/common/http";
import { Injectable } from "@angular/core";
import { Observable } from "rxjs";

@Injectable()
export class AuthInterceptor implements HttpInterceptor {

   private readonly _token: string = 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjU1MjZFOTU5RTYzOEE5NjNFMDY4NTJBQ0RFNTNEQjY0OEJEMzhBNDVSUzI1NiIsIng1dCI6IlZTYnBXZVk0cVdQZ2FGS3MzbFBiWkl2VGlrVSIsInR5cCI6ImF0K2p3dCJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdC9hdXRoIiwibmJmIjoxNzQ3MDc3NTU2LCJpYXQiOjE3NDcwNzc1NTYsImV4cCI6MTc0OTY2OTU1NiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbIkRFIEFkbWluIC0gUmVzZXJ2ZSIsIkRFIENlbnRyYWwgQm9hcmQgQWRtaW4iLCJFRk1QIENhc2UgTWFuYWdlbWVudCBVc2VyIiwiRUZNUCBDZW50cmFsIENlbGwgTWFuYWdlbWVudCIsIkVmbXBfQXNzaWdubWVudE5hdmlnYXRvciIsIkZ1bmN0aW9uYWwgRFQgQm9hcmQgQWRtaW4iLCJTdXJ2ZXkgQWRtaW4iLCJBRVRDIEFGRVJCIEFkbWluIiwiQUZERU1TIEFkbWluIiwiQUZFUkIgQUZJVCBBY2FkZW1pYyBDb2RpbmcgTWFuYWdlciIsIkFGRVJCIEFGSVQtQ0kgTWFuYWdlciIsIkFGRVJCIEFGSVQtRU4gTWFuYWdlciIsIkFGRVJCIFByb2dyYW0gTWFuYWdlciIsIkFGRVJCIFNwZWNpYWwgUHJvZ3JhbSBNYW5hZ2VyIiwiQUZFUkIgU1BFRUQgUHJvZ3JhbSBNYW5hZ2VyIiwiQUZQQyBTUEVFRCBBZG1pbiIsIkFzc2lnbm1lbnQgVGVhbSIsIkFzc2lnbm1lbnQgVGVhbSBNYW5hZ2VtZW50IExldmVsIiwiQ0ZNIiwiQ29vcmRpbmF0aW9ucyBXb3JrZmxvdyBBZG1pbiIsIkxvc2luZyBDb21tYW5kZXIiLCJNUEYgUmVsb2NhdGlvbnMgQWRtaW4iLCJSZXBvcnRpbmcgTWFuYWdlciIsIlNlbmlvciBMZWFkZXIgTWFuYWdlciIsIlN5c3RlbSBBZG1pbiIsIlVzZXIiLCJXb3JrY2VudGVyIEFkbWluIExlYWQiLCJXb3JrY2VudGVyIEFkbWluIiwiV29ya2NlbnRlciBVc2VyIiwiU3VydmV5IFNwYWNlIEFkbWluIl0sInBlcnNvbmlkIjoiMTAiLCJhdXRoZW50aWNhdGlvbm1ldGhvZHVzZWQiOiJJbXBlcnNvbmF0aW9uIiwic2Vzc2lvbmlkIjoiYzZkNGFiZmYtOWZlYS00ZmZlLTkxNzctNzQxYjNmMzYwNWExIiwicGVyc29uaWRlbnRpZmllciI6ImQwNGM5ZGM3LWQyNWItNDg4Yy04YmVmLWExNDFiNzFhNWY1ZSIsImRvZGlkIjoiIiwibGFzdGxvZ2luZGF0ZSI6IjIwMjUtMDUtMTIgMTc6NTU6NDMgXHUwMDJCMDAiLCJoYXNncm91cHMiOiJ0cnVlIn0.cjPVLtBVK9sWhq8qi87JVkjomnGsiS3r6N8Rt7p5n-oyhB8gYTuK-lODZvCzQFOA1JlHzi0-aPUBqIV18pymOqzAnLCjsTXsaOUXdqC2PxIJq2ze_nhmbalpaC0xENOPZWhomHVb3yhkUDSbd4dDMLcPSR9ql-ZoC5rTBELhxr5Apvev3avT8xWZhInV2Q2_G52BM1yb7XtSLKoUpviWcYWdgVvCGqHPsOPmwSgdQEtl8KOkKhT7g16Wh1a5qeZ6mVwdrdvMqnws3mPuE_odzctkJif_DpRbY6Dk68kPTcGoSXNPVfnpuWAhJ-Oxkpm1rHhHrzcfwQJ6XHOJGQPzog';
   intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
      request = request.clone({
         setHeaders: { Authorization: this._token }
      });
      return next.handle(request);
   }
}