import { HttpEvent, HttpHandler, HttpInterceptor, HttpRequest } from "@angular/common/http";
import { Injectable } from "@angular/core";
import { Observable } from "rxjs";

@Injectable()
export class AuthInterceptor implements HttpInterceptor {

    private readonly _token: string = "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjU1MjZFOTU5RTYzOEE5NjNFMDY4NTJBQ0RFNTNEQjY0OEJEMzhBNDVSUzI1NiIsIng1dCI6IlZTYnBXZVk0cVdQZ2FGS3MzbFBiWkl2VGlrVSIsInR5cCI6ImF0K2p3dCJ9.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdC9hdXRoIiwibmJmIjoxNzQ1OTMyOTkzLCJpYXQiOjE3NDU5MzI5OTMsImV4cCI6MTc0ODUyNDk5MywiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbIkFGREVNUyBBZG1pbiIsIkFGRVJCIFNwZWNpYWwgUHJvZ3JhbSBNYW5hZ2VyIiwiV29ya2NlbnRlciBBZG1pbiBMZWFkIiwiREUgQ2VudHJhbCBCb2FyZCBBZG1pbiIsIkFkbWluIiwiRGV2ZWxvcG1lbnQgUGxhbiBBZG1pbiIsIkFGRVJCIFNQRUVEIFByb2dyYW0gTWFuYWdlciIsIkVGTVAgQ2FzZSBNYW5hZ2VtZW50IFVzZXIiLCJBRkVSQiBBRklULUNJIE1hbmFnZXIiLCJERSBBZG1pbiAtIFJlc2VydmUiLCJBRkVSQiBBRklUIEFjYWRlbWljIENvZGluZyBNYW5hZ2VyIiwiU3VydmV5IEFkbWluIiwiQXNzaWdubWVudCBUZWFtIiwiQUZQQyBTUEVFRCBBZG1pbiIsIkFGRVJCIEFGSVQtRU4gTWFuYWdlciIsIkNGTSIsIlNlbmlvciBMZWFkZXIgTWFuYWdlciIsIkFFVEMgQUZFUkIgQWRtaW4iLCJGdW5jdGlvbmFsIERUIEJvYXJkIEFkbWluIiwiUmVwb3J0aW5nIE1hbmFnZXIiLCJFZm1wX0Fzc2lnbm1lbnROYXZpZ2F0b3IiLCJTeXN0ZW0gQWRtaW4iLCJFRk1QIENlbnRyYWwgQ2VsbCBNYW5hZ2VtZW50IiwiVXNlciIsIkxvc2luZyBDb21tYW5kZXIiLCJBc3NpZ25tZW50IFRlYW0gTWFuYWdlbWVudCBMZXZlbCIsIkNvb3JkaW5hdGlvbnMgV29ya2Zsb3cgQWRtaW4iLCJNUEYgUmVsb2NhdGlvbnMgQWRtaW4iLCJBRkVSQiBQcm9ncmFtIE1hbmFnZXIiLCJXb3JrY2VudGVyIEFkbWluIiwiV29ya2NlbnRlciBVc2VyIiwiU3VydmV5IFNwYWNlIEFkbWluIl0sInBlcnNvbmlkIjoiMTAiLCJhdXRoZW50aWNhdGlvbm1ldGhvZHVzZWQiOiJJbXBlcnNvbmF0aW9uIiwic2Vzc2lvbmlkIjoiYjAzMDQ1NTAtN2MyMy00YmVhLThlZGEtMDI5NTcyYjJiMDI0IiwicGVyc29uaWRlbnRpZmllciI6ImQwNGM5ZGM3LWQyNWItNDg4Yy04YmVmLWExNDFiNzFhNWY1ZSIsImRvZGlkIjoiIiwibGFzdGxvZ2luZGF0ZSI6IjIwMjUtMDQtMjMgMTM6NTE6NTkgXHUwMDJCMDAiLCJoYXNncm91cHMiOiJ0cnVlIn0.ve7P7gqCgAltwRov8R9hRrY_yVEDye9UIfahtlYGqzSXzVsoAJLIvHczUZsDveJMV2p-qTmChpMCwWLRFb4ovT6mMkjcfsH2oJuG1oooDBzcRAgDdfopz2IW_ZW8rvOIRAgCCFAIgmFF5A6-yVYVAMCXDWKrECvfux7-GetSTPeAm8OWmSwqghoIIJIALT1StE3FvwFcHTtfXgYdDLtT8OkpSTv_LOqL00t32WLB_E3_N8HHCfSX2niCY8dVgAHzij_tj_nGFzjsJkJBuL6EDQeLGAGm_o9zGN8YHARMO7f-DCkDqsMOsde5mWSFnwfJ1px4ysvw8S99zY-7lHFy9A"
    intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        // set token once logged in
        // if token is not set, get token
        // Add the token to the request
        request = request.clone({
            setHeaders: { Authorization: this._token }
        });
        return next.handle(request);
    }
}